# Generated by Django 3.1.5 on 2021-01-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_topic',
            new_name='topic',
        ),
    ]
